cacheFolder: "${YARN__CACHE_PATH_FOLDER:-./.yarn/cache}"

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

patchFolder: ./.yarn/patches

yarnPath: .yarn/releases/yarn-4.10.3.cjs
