cacheFolder: "${YARN__CACHE_PATH_FOLDER:-./.yarn/cache}"

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

patchFolder: ./.yarn/patches

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
