cacheFolder: "${YARN__CACHE_PATH_FOLDER:-./.yarn/cache}"

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

patchFolder: ./.yarn/patches

winLinkType: symlinks

yarnPath: .yarn/releases/yarn-4.5.2.cjs
