cacheFolder: "${YARN__CACHE_PATH_FOLDER:-./.yarn/cache}"

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

winLinkType: symlinks

patchFolder: ./.yarn/patches

yarnPath: .yarn/releases/yarn-4.4.1.cjs
